/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BEjZqQToQWB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function carousel() {
  return (
    <Carousel className="w-full">
      <CarouselContent>
        <CarouselItem>
          <div className="relative">
            <img
              alt="Carousel Image 1"
              className="aspect-[16/9] w-full object-cover"
              height={1080}
              src="/placeholder.svg"
              width={1920}
            />
            <div className="absolute inset-x-0 top-1/2 -translate-y-1/2 px-4 text-center md:px-6 lg:px-8">
              <h2 className="mb-2 text-2xl font-bold text-white md:text-3xl lg:text-4xl">
                Explore the Wonders of Nature
              </h2>
              <p className="text-lg text-gray-200 md:text-xl lg:text-2xl">
                Discover breathtaking landscapes and serene moments in the great outdoors.
              </p>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="relative">
            <img
              alt="Carousel Image 2"
              className="aspect-[16/9] w-full object-cover"
              height={1080}
              src="/placeholder.svg"
              width={1920}
            />
            <div className="absolute inset-x-0 top-1/2 -translate-y-1/2 px-4 text-center md:px-6 lg:px-8">
              <h2 className="mb-2 text-2xl font-bold text-white md:text-3xl lg:text-4xl">
                Embrace the Rhythm of the City
              </h2>
              <p className="text-lg text-gray-200 md:text-xl lg:text-2xl">
                Experience the vibrant energy and diverse culture of urban landscapes.
              </p>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="relative">
            <img
              alt="Carousel Image 3"
              className="aspect-[16/9] w-full object-cover"
              height={1080}
              src="/placeholder.svg"
              width={1920}
            />
            <div className="absolute inset-x-0 top-1/2 -translate-y-1/2 px-4 text-center md:px-6 lg:px-8">
              <h2 className="mb-2 text-2xl font-bold text-white md:text-3xl lg:text-4xl">
                Uncover the Secrets of the Past
              </h2>
              <p className="text-lg text-gray-200 md:text-xl lg:text-2xl">
                Delve into the rich history and captivating stories of ancient civilizations.
              </p>
            </div>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-white/50 p-2 text-gray-900 hover:bg-white/75 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-900 dark:bg-gray-900/50 dark:text-gray-50 dark:hover:bg-gray-900/75 dark:focus-visible:ring-gray-50">
        <ChevronLeftIcon className="h-6 w-6" />
      </CarouselPrevious>
      <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-white/50 p-2 text-gray-900 hover:bg-white/75 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-900 dark:bg-gray-900/50 dark:text-gray-50 dark:hover:bg-gray-900/75 dark:focus-visible:ring-gray-50">
        <ChevronRightIcon className="h-6 w-6" />
      </CarouselNext>
    </Carousel>
  )
}

function ChevronLeftIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
